// Contract Addresses - Auto-generated by deploy.sh
// Network: Localhost (Anvil)
// Deployed: Mon Oct 20 20:10:15 CEST 2025

export const CONTRACTS = {
  Token: '0x922D6956C99E12DFeB3224DEA977D0939758A1Fe' as `0x${string}`,
  IdentityRegistry: '0x1429859428C0aBc9C2C47C8Ee9FBaf82cFA0F20f' as `0x${string}`,
  TrustedIssuersRegistry: '0xB0D4afd8879eD9F52b28595d31B441D079B2Ca07' as `0x${string}`,
  ClaimTopicsRegistry: '0x162A433068F51e18b7d13932F27e66a3f99E6890' as `0x${string}`,
  MaxBalanceCompliance: '0x04C89607413713Ec9775E14b954286519d836FEf' as `0x${string}`,
  MaxHoldersCompliance: '0x21dF544947ba3E8b3c32561399E88B52Dc8b2823' as `0x${string}`,
  TransferLockCompliance: '0xD8a5a9b31c3C0232E196d518E89Fd8bF83AcAd43' as `0x${string}`,
} as const

export const CHAIN_CONFIG = {
  chainId: 31337,
  rpcUrl: 'http://localhost:8545',
  name: 'Localhost',
} as const

// Test accounts from Anvil
export const TEST_ACCOUNTS = {
  deployer: '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266' as `0x${string}`,
} as const
